var subscriberObj = {
    equipmentInfoField: {
        itemBrandField: 'not_set',
        itemIdField: '30609H',
        itemDescriptionField: 'SAMSUNG GALAXY J4 J400M GOLD',
        itemImageField: 'https://miclaro.clarotodo.com/ImageHandler/OracleImageHandler.ashx?DEVICE_ID=56571H',
        pricecodeField: null,
        installmentsField: null,
        installmentValueField: null,
        PropertyChanged: null,
        techField: 'LTE'
    },
    planInfoField: {
        sOCInfoField: 'FEBIS29L',
        sOCDescriptionField: 'VZ+MSG+LD+RM+DPRUSPUJ15GB',
        relatedSocCodeField: 'not_set',
        socRateField: 0,
        totalRateField: 0,
        commitmentStartDateField: '10/10/2018',
        mCommitmentOrigNoMonthField: null,
        commitmentEndDateField: '10/10/2019',
        effectiveDateField: '10/10/2018',
        PropertyChanged: null
    },
    usageInfoField: {
        dataOffersField: [
            {
                balancesField: {
                    subscriberIdField: '17872151740',
                    offerIdField: 'UNIM5GB',
                    balanceIdField: 'PR_USA_BalanceDef_10114',
                    balanceAmountField: '636909884',
                    balanceAmountUnitField: '607.4 MB',
                    effectiveDateField: '2019-02-03T00:00:00',
                    expiryDateField: '2019-03-03T00:00:00',
                    quotaRolloverField: '0',
                    quotaRolloverTextField: '0 OM',
                    PropertyChanged: null
                },
                subscriberIdField: '7872151740',
                quotaField: '5368709121',
                quotaTextField: '5 GB',
                displayNameField: 'IM Ilimitado PUJ 5GB PR',
                nameField: 'UNIM5GB',
                offerIdField: 'UNIM5GB',
                usedField: '636909884',
                usedTextField: '607.4 MB',
                offerGroupField: 'BASE NT_PROMO_NY16 POS UNLIMITED COMBOFFER_10165',
                groupIDField: null,
                endDateField: null,
                PropertyChanged: null
            },
            {
                balancesField: {
                    subscriberIdField: null,
                    offerIdField: null,
                    balanceIdField: null,
                    balanceAmountField: null,
                    balanceAmountUnitField: null,
                    effectiveDateField: null,
                    expiryDateField: null,
                    quotaRolloverField: null,
                    quotaRolloverTextField: '',
                    PropertyChanged: null
                },
                subscriberIdField: '7872151740',
                quotaField: '20971525',
                quotaTextField: '20 MB',
                displayNameField: 'Roaming Data a Granel',
                nameField: 'ROAMPYG',
                offerIdField: 'ROAMPYG',
                usedField: null,
                usedTextField: '0 MB',
                offerGroupField: 'POS LIMITED ROAMINGADDITIONAL NT_ROAM_GRANEL',
                groupIDField: null,
                endDateField: null,
                PropertyChanged: null
            }
        ],
        localBalanceField: '0',
        localTopField: '0MB',
        localDescriptionField: 'not_set',
        localPUJField: 'N',
        pUJTOPField: '0MB',
        roamBalanceField: '0',
        roamTopField: '0',
        minutesUsageField: '0',
        sMSUSageField: '0',
        mMSUsageField: '0',
        sMSPremiunUsageField: '0',
        roamingUsageField: '0',
        lDUsageField: '0',
        notificationField: '0%',
        PropertyChanged: null
    },
    additionalpackagesField: {
        localPackagesField: [
            {
                offerIdField: 'RUP250',
                nameField: 'RUP250',
                displayNameField: 'Booster Recurrente 250MB',
                isRecurringField: 'false',
                lengthField: '1',
                unitField: 'M',
                priceField: '$4.99',
                dPriceField: 4.99,
                volumeField: '262144000',
                volumeValueField: 0,
                volumeUnitField: '250 MB',
                offerGroupField: 'ADDITIONAL, AUTOTOPUP_5, PRICE_4,99, POS, UNLIMITED, NT_ADD_UNLIMITED_RECUR, ',
                PropertyChanged: null
            },
            {
                offerIdField: 'UP250',
                nameField: 'UP250',
                displayNameField: 'Booster 250MB',
                isRecurringField: 'false',
                lengthField: '1',
                unitField: 'M',
                priceField: '$4.99',
                dPriceField: 4.99,
                volumeField: '262144000',
                volumeValueField: 0,
                volumeUnitField: '250 MB',
                offerGroupField: 'ADDITIONAL, POS, UNLIMITED, NT_ADD_UNLIMITED, ',
                PropertyChanged: null
            },
            {
                offerIdField: 'RUP1GB',
                nameField: 'RUP1GB',
                displayNameField: 'Booster Recurrente 1GB',
                isRecurringField: 'false',
                lengthField: '1',
                unitField: 'M',
                priceField: '$9.99',
                dPriceField: 9.99,
                volumeField: '1073741824',
                volumeValueField: 0,
                volumeUnitField: '1 GB',
                offerGroupField: 'ADDITIONAL, AUTOTOPUP_5, POS, PRICE_9,99, UNLIMITED, NT_ADD_UNLIMITED_RECUR, ',
                PropertyChanged: null
            },
            {
                offerIdField: 'UP1GB',
                nameField: 'UP1GB',
                displayNameField: 'Booster 1GB',
                isRecurringField: 'false',
                lengthField: '1',
                unitField: 'M',
                priceField: '$9.99',
                dPriceField: 9.99,
                volumeField: '1073741824',
                volumeValueField: 0,
                volumeUnitField: '1 GB',
                offerGroupField: 'ADDITIONAL, POS, UNLIMITED, NT_ADD_UNLIMITED, ',
                PropertyChanged: null
            },
            {
                offerIdField: 'RUP3GB',
                nameField: 'RUP3GB',
                displayNameField: 'Booster Recurrente 3GB',
                isRecurringField: 'false',
                lengthField: '1',
                unitField: 'M',
                priceField: '$19.99',
                dPriceField: 19.99,
                volumeField: '3221225472',
                volumeValueField: 0,
                volumeUnitField: '3 GB',
                offerGroupField: 'ADDITIONAL, AUTOTOPUP_5, PRICE_19,99, POS, UNLIMITED, NT_ADD_UNLIMITED_RECUR, ',
                PropertyChanged: null
            },
            {
                offerIdField: 'UP3GB',
                nameField: 'UP3GB',
                displayNameField: 'Booster 3GB',
                isRecurringField: 'false',
                lengthField: '1',
                unitField: 'M',
                priceField: '$19.99',
                dPriceField: 19.99,
                volumeField: '3221225472',
                volumeValueField: 0,
                volumeUnitField: '3 GB',
                offerGroupField: 'ADDITIONAL, POS, UNLIMITED, NT_ADD_UNLIMITED, ',
                PropertyChanged: null
            },
            {
                offerIdField: 'UP5GB',
                nameField: 'UP5GB',
                displayNameField: 'Booster 5GB',
                isRecurringField: 'false',
                lengthField: '1',
                unitField: 'M',
                priceField: '$24.99',
                dPriceField: 24.99,
                volumeField: '5368709120',
                volumeValueField: 0,
                volumeUnitField: '5 GB',
                offerGroupField: 'ADDITIONAL, POS, UNLIMITED, NT_ADD_UNLIMITED, ',
                PropertyChanged: null
            },
            {
                offerIdField: 'RUP5GB',
                nameField: 'RUP5GB',
                displayNameField: 'Booster Recurrente 5GB',
                isRecurringField: 'false',
                lengthField: '1',
                unitField: 'M',
                priceField: '$24.99',
                dPriceField: 24.99,
                volumeField: '5368709120',
                volumeValueField: 0,
                volumeUnitField: '5 GB',
                offerGroupField: 'PRICE_24,99, ADDITIONAL, AUTOTOPUP_5, POS, UNLIMITED, NT_ADD_UNLIMITED_RECUR, ',
                PropertyChanged: null
            }
        ],
        roamingPackagesField: [
            {
                offerIdField: 'ROA120',
                nameField: 'ROA120',
                displayNameField: 'Data Roam Int 120MB',
                isRecurringField: 'false',
                lengthField: '1',
                unitField: 'M',
                priceField: '$30.00',
                dPriceField: 30,
                volumeField: '125829120',
                volumeValueField: 0,
                volumeUnitField: '120 MB',
                offerGroupField: 'NT_ADD_ROAM_LIMITED, POS, LIMITED, ROAMINGADDITIONAL, ',
                PropertyChanged: null
            },
            {
                offerIdField: 'ROA350',
                nameField: 'ROA350',
                displayNameField: 'Data Roam Int 350MB',
                isRecurringField: 'false',
                lengthField: '1',
                unitField: 'M',
                priceField: '$60.00',
                dPriceField: 60,
                volumeField: '367001600',
                volumeValueField: 0,
                volumeUnitField: '350 MB',
                offerGroupField: 'NT_ADD_ROAM_LIMITED, POS, LIMITED, ROAMINGADDITIONAL, ',
                PropertyChanged: null
            },
            {
                offerIdField: 'ROA850',
                nameField: 'ROA850',
                displayNameField: 'Data Roam Int 850MB',
                isRecurringField: 'false',
                lengthField: '1',
                unitField: 'M',
                priceField: '$120.00',
                dPriceField: 120,
                volumeField: '891289600',
                volumeValueField: 0,
                volumeUnitField: '850 MB',
                offerGroupField: 'NT_ADD_ROAM_LIMITED, POS, LIMITED, ROAMINGADDITIONAL, ',
                PropertyChanged: null
            }
        ],
        PropertyChanged: null
    },
    servEquipmentSerialsField: {
        servEquipmentSerialField: [
            {
                itemIdField: '30609H         ',
                equipmentTypeField: 'J',
                eSNField: '357501096227869',
                PropertyChanged: null
            }
        ],
        PropertyChanged: null
    },
    servSVAInfoField: {
        servSVAsField: [],
        PropertyChanged: null
    },
    subscriberNumberField: '7872151740',
    productTypeField: 'G',
    subscriberStatusField: 'A',
    prepaidBalanceField: null,
    localBalanceField: null,
    reasonCodeField: null,
    groupIDField: null,
    hasErrorField: false,
    errorDescField: null,
    errorNumField: 0,
    PropertyChanged: null
}